sudo: false
language:
  - generic
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: precise
      sudo: false
    - os: osx
addons:
  apt:
    sources:
      - cassou-emacs
    packages:
      - git
      - emacs24-nox
      - wget
      - curl
install:
  - if [ $TRAVIS_OS_NAME = "osx" ]; then brew update -y; brew install wget emacs git curl || true; fi
  - if [ $TRAVIS_OS_NAME != "osx" ]; then sudo apt-get install -qq -y git emacs24-nox wget curl || true; fi
before_script:
  - rm -rf $HOME/.emacs.d
  - ln -s `pwd` $HOME/.emacs.d
script:
  - emacs -batch --eval '(setq debug-on-error t)' -l init.el
