language:
  - generic
matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
  allow_failures:
    - env:
        os: osx
addons:
  apt:
    packages:
      - git
      - emacs24-nox
      - wget
      - curl
      - make
      - texinfo
install:
  - if [ $TRAVIS_OS_NAME = "osx" ]; then brew update -y; brew install wget emacs git curl || true; fi
  - if [ $TRAVIS_OS_NAME != "osx" ]; then sudo apt-get install -qq -y git emacs24-nox wget curl make texinfo || true; fi
before_script:
  - rm -rf $HOME/.emacs.d
  - ln -s `pwd` $HOME/.emacs.d
script:
  - emacs -batch --eval '(setq debug-on-error t)' -l init.el
after_script:
  - emacs -batch -l .travis-show-log.el
